### ISSUE TITLE
Are tox21.parquet and tox21_aggregated.parquet supposed to be the same?

### ISSUE THREAD

**Issue by zmughal** [biobricks-ai/tox21#3]
I see that on https://github.com/biobricks-ai/tox21/blob/5c16c5012ef64298a947a857c190d50aabe45383/stages/3_write_brick.R#L22-L23

it writes `aggmerge` when it may need to be `rawmerge`.

I have a local branch with a fix for this.

And also another unrelated fix for path processing at https://github.com/biobricks-ai/tox21/blob/5c16c5012ef64298a947a857c190d50aabe45383/stages/2_unzip.sh#L33 .

**Comment by tomlue** [comment]
Should be able to look at this tomorrow. If you feel somewhat confident that they are the same then you sold mine forward with your fix
